export const STARTINGSCREEN = "STARTINGSCREEN";
export const ENDGAME = "ENDGAME";
export const SUPERHERO = "SUPERHERO";
export const START_TIMER = "START_TIMER";
export const LEVEL_OF_DIFFICULT = "LEVEL_OF_DIFFICULT";
export const SCORE = "SCORE";
export const YOUR_FAILED = "YOUR_FAILED";
export const UPDATEENEMYFIELD = "UPDATEENEMYFIELD";